import sgMail from '@sendgrid/mail';

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const FROM_EMAIL = process.env.SENDGRID_FROM_EMAIL || 'noreply@furrowag.com';

if (SENDGRID_API_KEY) {
  sgMail.setApiKey(SENDGRID_API_KEY);
}

function isEnabled(): boolean {
  return !!SENDGRID_API_KEY;
}

async function send(to: string, subject: string, html: string): Promise<void> {
  if (!isEnabled()) {
    console.log(`[EmailService] Would have sent email to ${to}: "${subject}"`);
    return;
  }
  await sgMail.send({ to, from: FROM_EMAIL, subject, html });
}

export interface InvoiceEmailData {
  recipientEmail: string;
  invoiceNumber: string;
  poNumber: string;
  buyerName: string;
  growerName: string;
  totalTons: number;
  pricePerTon: number;
  totalAmount: number;
}

export async function sendInvoiceEmail(data: InvoiceEmailData): Promise<void> {
  const html = `
    <h2>Invoice ${data.invoiceNumber}</h2>
    <p>Purchase Order: <strong>${data.poNumber}</strong></p>
    <table style="border-collapse:collapse;width:100%;max-width:500px">
      <tr><td style="padding:4px 8px">Buyer</td><td style="padding:4px 8px"><strong>${data.buyerName}</strong></td></tr>
      <tr><td style="padding:4px 8px">Grower</td><td style="padding:4px 8px"><strong>${data.growerName}</strong></td></tr>
      <tr><td style="padding:4px 8px">Total Tons</td><td style="padding:4px 8px">${data.totalTons.toFixed(2)}</td></tr>
      <tr><td style="padding:4px 8px">Price/Ton</td><td style="padding:4px 8px">$${data.pricePerTon.toFixed(2)}</td></tr>
      <tr><td style="padding:4px 8px;border-top:2px solid #333"><strong>Total</strong></td><td style="padding:4px 8px;border-top:2px solid #333"><strong>$${data.totalAmount.toFixed(2)}</strong></td></tr>
    </table>
    <p style="margin-top:16px;color:#666">This invoice was auto-generated by Furrow Ag.</p>
  `;
  await send(data.recipientEmail, `Invoice ${data.invoiceNumber} — ${data.growerName}`, html);
}

export interface POStatusNotificationData {
  recipientEmail: string;
  poNumber: string;
  oldStatus: string;
  newStatus: string;
  orgName: string;
}

export async function sendPOStatusNotification(data: POStatusNotificationData): Promise<void> {
  const html = `
    <h2>Purchase Order Status Update</h2>
    <p>PO <strong>${data.poNumber}</strong> has been updated.</p>
    <p>Status: <strong>${data.oldStatus}</strong> → <strong>${data.newStatus}</strong></p>
    <p>Organization: ${data.orgName}</p>
  `;
  await send(data.recipientEmail, `PO ${data.poNumber} — Status changed to ${data.newStatus}`, html);
}

export interface LoadDeliveryConfirmationData {
  recipientEmail: string;
  loadNumber: string;
  poNumber: string;
  netWeight: number;
  totalBaleCount: number;
  deliveryDate: string;
}

export async function sendLoadDeliveryConfirmation(data: LoadDeliveryConfirmationData): Promise<void> {
  const html = `
    <h2>Delivery Confirmed</h2>
    <p>Load <strong>${data.loadNumber}</strong> has been delivered.</p>
    <table style="border-collapse:collapse">
      <tr><td style="padding:4px 8px">Purchase Order</td><td style="padding:4px 8px"><strong>${data.poNumber}</strong></td></tr>
      <tr><td style="padding:4px 8px">Net Weight</td><td style="padding:4px 8px">${data.netWeight.toFixed(0)} lbs</td></tr>
      <tr><td style="padding:4px 8px">Bale Count</td><td style="padding:4px 8px">${data.totalBaleCount}</td></tr>
      <tr><td style="padding:4px 8px">Date</td><td style="padding:4px 8px">${data.deliveryDate}</td></tr>
    </table>
  `;
  await send(data.recipientEmail, `Delivery Confirmed — Load ${data.loadNumber}`, html);
}
