import prisma from '../config/database';
import { sendInvoiceEmail } from './emailService';

const INVOICE_NUMBER_START = 1001;

async function generateInvoiceNumber(): Promise<string> {
  const last = await prisma.invoice.findFirst({
    orderBy: { invoiceNumber: 'desc' },
    select: { invoiceNumber: true },
  });
  if (!last) return `INV-${INVOICE_NUMBER_START}`;
  const num = parseInt(last.invoiceNumber.replace('INV-', ''), 10);
  return `INV-${isNaN(num) ? INVOICE_NUMBER_START : num + 1}`;
}

export async function autoGenerateInvoice(poId: string) {
  const po = await prisma.purchaseOrder.findUnique({
    where: { id: poId },
    include: {
      buyerOrg: true,
      growerOrg: true,
      loads: {
        where: { status: 'CONFIRMED' },
        select: { grossWeight: true, tareWeight: true },
      },
    },
  });

  if (!po) throw new Error(`PO ${poId} not found`);

  // Calculate total tons from confirmed loads
  const totalTons = po.loads.reduce((sum, l) => {
    const net = (l.grossWeight ?? 0) - (l.tareWeight ?? 0);
    return sum + net / 2000;
  }, 0);

  const roundedTons = Math.round(totalTons * 100) / 100;
  const subtotal = roundedTons * po.pricePerTon;
  const totalAmount = Math.round(subtotal * 100) / 100;

  const invoiceNumber = await generateInvoiceNumber();

  const invoice = await prisma.invoice.create({
    data: {
      invoiceNumber,
      poId: po.id,
      growerOrgId: po.growerOrgId,
      buyerOrgId: po.buyerOrgId,
      totalTons: roundedTons,
      pricePerTon: po.pricePerTon,
      subtotal: totalAmount,
      totalAmount,
      autoGenerated: true,
    },
  });

  return invoice;
}

export async function sendInvoice(invoiceId: string) {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      po: { select: { poNumber: true } },
      buyerOrg: { select: { name: true, invoiceEmail: true } },
      growerOrg: { select: { name: true } },
    },
  });

  if (!invoice) throw new Error(`Invoice ${invoiceId} not found`);

  const recipientEmail = invoice.buyerOrg.invoiceEmail;
  if (!recipientEmail) {
    console.log(`[InvoiceService] No invoiceEmail configured for buyer org ${invoice.buyerOrg.name}, skipping send`);
    return invoice;
  }

  await sendInvoiceEmail({
    recipientEmail,
    invoiceNumber: invoice.invoiceNumber,
    poNumber: invoice.po.poNumber,
    buyerName: invoice.buyerOrg.name,
    growerName: invoice.growerOrg.name,
    totalTons: invoice.totalTons,
    pricePerTon: invoice.pricePerTon,
    totalAmount: invoice.totalAmount,
  });

  const updated = await prisma.invoice.update({
    where: { id: invoice.id },
    data: {
      sentToEmail: recipientEmail,
      sentAt: new Date(),
      emailDeliveryStatus: 'sent',
    },
  });

  return updated;
}
